GET https://hidden-taiga-63637.herokuapp.com/api/v1/flower

###
POST https://hidden-taiga-63637.herokuapp.com/api/v1/flower
Content-Type: application/json

{
  "sepalLength": 100,
  "color": "blue",
  "price": 100
}